RAM=6144
CPU=5
DISKS=(
    -drive "file=${IMAGES_DIR}/agnes.img,index=0,media=disk,if=ide"
)
NETWORK=(
    -netdev user,id=net0,hostfwd=tcp::443-:443,hostfwd=tcp::1337-:1337,hostfwd=tcp::2212-:2212,hostfwd=tcp::4445-:4445
    -device e1000,netdev=net0
)
