RAM=5120
CPU=4
DISKS=(
    -drive "file=${IMAGES_DIR}/agnes.img,index=0,media=disk,if=ide"
)
NETWORK=(
    -netdev user,id=net0,hostfwd=tcp::2212-:2212,tcp::4445-:4445
    -device e1000,netdev=net0
)
