RAM=5120
CPU=4
DISKS=(
    -drive "file=${IMAGES_DIR}/agnes.img,index=0,media=disk,if=ide"
)
NETWORK=(
    -netdev tap,id=net0,script=no,downscript=no
    -device e1000,netdev=net0,mac=fa:68:90:d3:5f:dc
)
BEFORE_QEMU=(
    "${LIB_DIR}/configure-bridge.sh"
    "${LIB_DIR}/configure-nft.sh"
)
USB=(
    -chardev serial,path=/dev/ttyACM0,id=acm
    -usb -device usb-serial,chardev=acm
)
