RAM=5120
CPU=4

IMAGES_DIR=${IMAGES_DIR:?set IMAGES_DIR}
LIB_DIR=${LIB_DIR:?set LIB_DIR}

# Network parameters (make them explicit so scripts don't hardcode)
BRIDGE_IF=br0
TAP_IF=tap0
BRIDGE_ADDR=15.10.0.7/24
VM_NET=15.10.0.0/24
WAN_IF=enp0s31f6

DISKS=(
  -drive "file=${IMAGES_DIR}/agnes.img,index=0,media=disk,if=ide"
)

NETWORK=(
  -netdev "tap,id=net0,ifname=${TAP_IF},script=no,downscript=no"
  -device e1000,netdev=net0,mac=fa:68:90:d3:5f:dc
)

BEFORE_QEMU=(
  "${LIB_DIR}/configure-bridge.sh"
)

AFTER_QEMU=(
  "${LIB_DIR}/configure-tap_and_route.sh"
  "${LIB_DIR}/configure-nft.sh"
)

CLEANUP=(
  "${LIB_DIR}/cleanup-network.sh"
)
