RAM=4096
CPU=3
DISKS=(
    -drive "file=${IMAGES_DIR}/windows.img"
)
NETWORK=(
    -netdev user,id=net0,hostfwd=tcp::2222-:2222,hostfwd=tcp::3389-:3389
    -device e1000,netdev=net0
)
BIOS=(
    -bios "${IMAGES_DIR}/OVMF_CODE.fd"
)
BEFORE_QEMU=(
    "${LIB_DIR}/configure-bridge.sh"
    "${LIB_DIR}/configure-nft.sh"
)
