RAM=4096
CPU=2
DISKS=(
    -drive "file=${IMAGES_DIR}/windows.img"
)
NETWORK=(
    -netdev tap,id=net1,script=no,downscript=no
    -device e1000,netdev=net1
)
BIOS=(
    -bios "${IMAGES_DIR}/OVMF_CODE.fd"
)
BEFORE_QEMU=(
    "${LIB_DIR}/configure-bridge.sh"
    "${LIB_DIR}/configure-nft.sh"
)
